# Generated by Django 3.2.16 on 2022-11-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myprofilemodel_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='frown', max_length=50)),
                ('text_file', models.FileField(upload_to='images/uploads/%Y/%m/%d')),
                ('audio_file', models.FileField(upload_to='images/uploads/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'force_alignments',
                'db_table': 'force_alignment',
            },
        ),
    ]
