# Generated by Django 3.2.16 on 2022-11-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20221120_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignmentmodel',
            name='json_file',
        ),
        migrations.AddField(
            model_name='alignmentmodel',
            name='transcription_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='alignmentmodel',
            name='audio_file',
            field=models.FileField(default='image.jpg', null=True, upload_to='audio/uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='alignmentmodel',
            name='text_file',
            field=models.FileField(default='image.jpg', null=True, upload_to='images/uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='alignmentmodel',
            name='video_file',
            field=models.FileField(default='image.jpg,', null=True, upload_to='videos/uploads/%Y/%m/%d'),
        ),
    ]
