version: "3.3"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend
    command: >
            sh -c "cd /app/backend &&
            python manage.py wait_for_db &&
            python3 manage.py makemigrations && 
            python3 manage.py migrate && 
            python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/backend/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    hostname: backend
    networks:
      - main
    env_file:
      - ./.env/dev.env
    # docker exec -it <container_id> python manage.py createsuperuser

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/posgresql/data
    networks:
      - main

  gentle:
    ports:
      - 8003:8765
    image: lowerquality/gentle
    volumes:
      - .:/app
      - .backend:/test

networks:
  main:

volumes:
  pgdata:
  static_volume:

# docker run --privileged --rm tonistiigi/binfmt --install amd64
# docker run -p 8765 --platform=linux/amd64 lowerquality/gentle