FROM continuumio/miniconda3
RUN conda create -n aligner -c conda-forge montreal-forced-aligner
RUN conda install -c conda-forge python=3.8 kaldi sox librosa biopython praatio tqdm requests colorama pyyaml pynini openfst baumwelch ngram